import * as core from '@actions/core';
import * as path from 'path';

import { getSortedEntries, readLines, writeLines } from './fs-utils';
import { ActionContext } from './types';
import {
    addGeneratedMarker,
    buildManualWikiKeepSet,
    ensureWritableWikiTarget,
} from './wiki-manual';
import { updateFileLinks } from './wiki-links';
import {
    convertToWikiFileName,
    getOutputFileNameFromPath,
    getRepoRelativePath,
    getSourceRelativePath,
} from './wiki-paths';

const SOURCE_FILE_LINK_TOKEN = /\{sourceFileLink\}/g;

export {
    addGeneratedMarker,
    buildManualWikiKeepSet,
} from './wiki-manual';
export { updateFileLinks } from './wiki-links';
export {
    convertToWikiFileName,
    getOutputFileNameFromPath,
} from './wiki-paths';

async function visitMarkdownFiles(
    directoryPath: string,
    directories: string[],
    visitor: (sourceFilePath: string, fileName: string, directories: string[]) => Promise<void>,
): Promise<void> {
    const entries = await getSortedEntries(directoryPath);

    for (const entry of entries) {
        if (!entry.isFile() || !entry.name.toLowerCase().endsWith('.md')) {
            continue;
        }

        await visitor(path.join(directoryPath, entry.name), entry.name, directories);
    }

    for (const entry of entries) {
        if (!entry.isDirectory()) {
            continue;
        }

        await visitMarkdownFiles(
            path.join(directoryPath, entry.name),
            directories.concat(entry.name),
            visitor,
        );
    }
}

function addCustomHeader(
    fileName: string,
    directories: string[],
    content: string[],
    context: ActionContext,
): string[] {
    const relativePath = getRepoRelativePath(fileName, directories, context.rootDocsFolderDirs);
    const sourceFileLink =
        `${context.repositoryUrl}/blob/${context.defaultBranch}/${relativePath}`;
    const header = context.customWikiFileHeaderFormat.replace(
        SOURCE_FILE_LINK_TOKEN,
        sourceFileLink,
    );

    return [header, '', '', ...content];
}

async function processSourceFile(
    sourceFilePath: string,
    fileName: string,
    directories: string[],
    context: ActionContext,
): Promise<void> {
    core.debug(`Processing file ${sourceFilePath}`);

    const sourceRelativePath = getSourceRelativePath(fileName, directories);
    const outputFileName = context.sourceFileToWikiFileNameMap.get(sourceRelativePath);

    if (!outputFileName) {
        throw new Error(`Missing wiki output name for ${sourceRelativePath}`);
    }

    let content = await readLines(sourceFilePath);
    content = updateFileLinks(
        fileName,
        directories,
        content,
        context.repositoryUrl,
        context.defaultBranch,
        context.rootDocsFolderDirs,
        context.sourceFileToWikiFileNameMap,
    );

    if (context.customWikiFileHeaderFormat && fileName.toLowerCase() !== '_sidebar.md') {
        content = addCustomHeader(fileName, directories, content, context);
    }

    const outputPath = path.join(context.wikiRepoPath, outputFileName);
    await ensureWritableWikiTarget(outputPath);
    await writeLines(outputPath, addGeneratedMarker(content));
}

export async function buildSourceFileMap(
    directoryPath: string,
    directories: string[],
    context: ActionContext,
): Promise<void> {
    await visitMarkdownFiles(directoryPath, directories, async (_sourceFilePath, fileName, fileDirectories) => {
        const sourceRelativePath = getSourceRelativePath(fileName, fileDirectories);
        const outputFileName = getOutputFileNameFromPath(
            fileName,
            fileDirectories,
            context.convertRootReadmeToHomePage,
        );
        const existingSourceFile = context.wikiFileNameToSourceFileMap.get(outputFileName);

        if (existingSourceFile) {
            throw new Error(
                `Wiki file name ${outputFileName} would be generated by both ${existingSourceFile} and ${sourceRelativePath}`,
            );
        }

        context.sourceFileToWikiFileNameMap.set(sourceRelativePath, outputFileName);
        context.wikiFileNameToSourceFileMap.set(outputFileName, sourceRelativePath);
    });
}

export async function processSourceDirectory(
    directoryPath: string,
    directories: string[],
    context: ActionContext,
): Promise<void> {
    await visitMarkdownFiles(directoryPath, directories, async (sourceFilePath, fileName, fileDirectories) => {
        await processSourceFile(sourceFilePath, fileName, fileDirectories, context);
    });
}
